name = "litora-site-screenshot"
main = "src/index.ts"
compatibility_date = "2025-08-16"

account_id = "641026e0b6ea7699bb5b7f599727e403"

[observability]
enabled = true

[[kv_namespaces]]
binding = "IMAGES"
id = "5814478b6ed440668ec19b07b5760238"
